### ISSUE TITLE
İçerik Sorunu

### ISSUE THREAD

**Issue by hcemaras** [Ludeon/RimWorld-Turkish#104]
Merhaba arkadaşlar
Elimde İngilizce dil dosyaları da bulunuyor ve bunları Buradaki Türkçe fil dosyaları ile karşılaştırdığımda içeriklerin bazılarının uyuşmadığını görüyorum. Elimdeki alfa 14 sürümü, başka sürümde içerikler farklı olup olmadığını bilmediğimden bu projede kullanabileceğim orijinal İngilizce dil dosyalarını nereden bulabilirim?
Teşekkürler

**Comment by Ferhatyesil** [comment]
Kendiniz eklemelisiniz hazir olarak bulunmamakta.

24 Ağu 2016 12:49 tarihinde "Hüseyin Cem Aras" <notifications@github.com>
yazdı:

**Comment by Ferhatyesil** [comment]
Eğer Defİnjected'dan bahsediyorsak dediğim gibi kendimiz yazmalıyız.  (https://ludeon.com/forums/index.php?topic=2933.0) [Son kısımda Yazmakta.]

"Keys-String-worldbank" = bunlar orjinal olarak bulunmakta

**Comment by hcemaras** [comment]
Sürümler arasında değişiklik olmuyorsa ben alfa 14 ün dosyalarını kullanacağım. hayvan isimlerinde çok büyük bir sıkıntı vardı çoğu isme boğa denmişti, onları alfa 14 e göre düzenledim umarım bir sürüm farklılığı yoktur.

**Comment by Ferhatyesil** [comment]
Telefon numaraniz varsa sizle iletisime gecebilir miyim?

24 Ağu 2016 16:00 tarihinde "Hüseyin Cem Aras" <notifications@github.com>
yazdı:

**Comment by Ferhatyesil** [comment]
Ysllferhat@gmail.com
Ozelden atarsaniz daha rahat anlaşiriz.
