### ISSUE TITLE
Çeviri Biçimlendirmesi Hk. 

### ISSUE THREAD

**Issue by ahmetcanaydemir** [Ludeon/RimWorld-Turkish#112]
Gördüğüm kadarı ile çeviriler birbirinden farklı biçimlere göre yapılıyor ve oyunun içine girince çeviriler saçma sapan bir hal alıyor. Hatta ne demek istediği anlaşılmıyor. 

Örnek vermek gerekirse. 
Bazı yerlerde "Lütfen tıklayınız" çevirisi yapılmışken başka bir yerde "Lütfen tıkla" yazmış. 

Bir başka yerde de your tech level "benim teknoloji seviyem" olarak çevrilmiş. 

Hal böyle olunca oyunu ingilizce oynamak daha mantıklı oluyor.

Bunu önlemek için Readme.md'ye bir biçim kılavuzu eklenebilir.

**Comment by hcemaras** [comment]
Biçim kılavuzundan kastınız ne ben anlayamadım bilmediğim bir düzenleme olabilir. Ek olarak çeviriler konusunda,  yeni üyeler ile birlikte aktif bir ekip kurabiliriz bu sayede iş birliği yaparak çoğu eksikliği tamamlayabiliriz.

**Comment by Zamahoya** [comment]
mesela bir whatsapp grubu olabilir bu eğer size bir sorun teşkil
etmiyecekse telefon numaranızı vermek

13 Eylül 2016 23:38 tarihinde Hüseyin Cem Aras <notifications@github.com>
yazdı:

**Comment by Ferhatyesil** [comment]
Whatsapp grubumuzu açtık remzi beyfendi ile özel e-posta ile numarinizi
atarsaniz ekleyebilirim.

14 Eyl 2016 00:19 tarihinde "Remzi Baskent" <notifications@github.com>
yazdı:

**Comment by hcemaras** [comment]
Gönderdim
