### ISSUE TITLE
Küçük harf kullanılan kelimeler hakkında

### ISSUE THREAD

**Issue by ahmetcanaydemir** [Ludeon/RimWorld-Turkish#131]
Orijinalinde küçük harf kullanılan kelime ve cümlelerin baş harflerini neden büyük harf yapıyorsunuz. Özellikle küçük harfli olduklarını düşünüyorum.

Ek olarak colonist kelimesi için ortak bir karar alınması gerektiği kanısındayım. Bazı yerlerde kolonist bazı yerlerde kolonici olarak çevrilmiş.

**Comment by hcemaras** [comment]
"colonist" tam olarak türkçe çevirisi "sömürgeci" oluyor. Fakat koloni kelimesi tabanlı bir çeviri istiyorsanız- kolonici daha çok meslek adını benzemektedir fakat biz bir üyeden bahsediyoruz bu yüzden kolonist uygundur,

**Comment by Slevilex** [comment]
"Vatandaş"'ın da uygun olabileceğini düşünüyorum.
