### ISSUE TITLE
Türkçe Çeviri Ekibi

### ISSUE THREAD

**Issue by dayzbrk** [Ludeon/RimWorld-Turkish#216]
...

**Comment by Slevilex** [comment]
TEOG derdiyle uğraşıyorum ve mümkün olduğunca ilgilenmeye çalışıyorum. Kurs
okul vb. derken ne kadar uğraştığımı anlayamıyorsunuz. O "Adamın" boş
zamanı varmış. Fakat bu gruptaki herkesin işi gücü var. Öyle rahat ekmek
elden su gölden değil yani.

-Samet Ahmet Şahin(Slevilex)

12 Ocak 2017 Perşembe tarihinde, dayzbrk <notifications@github.com> yazdı:

**Comment by Slevilex** [comment]
Sen gram çeviri işi ile uğraşmıyorken gelip bize laga luga yapıyorsun.

**Comment by hcemaras** [comment]
Eleştiriniz için teşekkürler, yeterli olmadığımızdan çeviri işinde bizi yardım etmek ister misiniz? demek uygun olabilirdi, lakin Türkçeyi düzgün kullanamıyorsunuz. ("türkçeleştirmeyi geliştirmek?", "çıkın_da", "olmuyo(r)sunuz").
Lütfen bir dahaki eleştirilerinizde, olumsuz ifadeleri kullanarak bir grup insanı negatif etkilemeyin, bir durumu anlatmanın birden fazla yolu vardır.
İyi günler...

**Comment by dayzbrk** [comment]
sinirle yazmıştım işe yaramış update gelmiş :D

**Comment by hcemaras** [comment]
Adam kim?
Gönüllü çalışıyoruz. Boş konuşmuyoruz.

**Comment by Hakkiro** [comment]
Arkadaşlar herkese kolay gelsin. Ekibe yeni katıldım. Ve gerçekten yardımcı olmak istiyorum. Nereden başlamalıyım ? Size nasıl ulaşırım? Bana 1-2 örnekte yardımcı olursanız geri kalanı halledebilirim diyedüşünüyorum.

**Comment by Ferhatyesil** [comment]
İyi Günler e-postama Telefon numaranı atarsan Whatsapp grubuna alabilirim.
E-posta = ysllferhat@gmail.com

**Comment by hcemaras** [comment]
Wp grubundan yardımcı olabiliriz, aramıza hoşgeldin 😊

**Comment by Hakkiro** [comment]
Ferhat ben mail attım sana ama görmedin sanırım. mail adresim buyukada_hakan@hotmail.com skyp üzerindewnde ulaşailirsiniz. ben baya bişeyler yaptım ama umarım doğru yapmışımdır.
Bu arada Hüseyin Backstorye dokunmuyorum sen çalışıyosun üzerinde şu diger dosyalar bittiğinde onada bakarım.
