### ISSUE TITLE
"Urbworld" kelimesinin tam olarak çevirisi?

### ISSUE THREAD

**Issue by Slevilex** [Ludeon/RimWorld-Turkish#219]

**Comment by hcemaras** [comment]
**Urbworld = Urban + World**

urban=kentsel- world=dünya
_Urbworld=Kentdünya_ 

urban=şehirsel - world=alem
_Urbworld=Şehralem_

**Comment by Hakkiro** [comment]
belki şuradan geliyor olabilir. Urban+World = Urbworld kentsel dünya..

**Comment by Hakkiro** [comment]
ahaha hüseyin senin yazdığını görmeden yazmıstım :D

**Comment by hcemaras** [comment]
Evet hızına şaşırdım, bir an benden önce mi attı diye baktım :D

**Comment by Slevilex** [comment]
Tam emin olamadığım için size sordum , ortak bir karar alalım diye. Ben de
kentya tarzı bir şey düşünmüştüm de.

2017-01-31 12:29 GMT+02:00 Hüseyin Cem Aras <notifications@github.com>:

**Comment by hcemaras** [comment]
kentya da güzel, amacına hizmet ediyor. Ben bir kaç yerde kentdünya kullandım. Seçeceğimiz kelimeye göre düzenleme yaparım.

**Comment by hcemaras** [comment]
Yapacağımız seçim ek bakımından uygun olsun, **urbworld** gibi **glitterworld** de var. Aynı eki ikisinde de kullanabilmemiz gerekiyor.

**Comment by Slevilex** [comment]
Glitterworld için "Gelya" da olabilir , diğeri gibi kısa. "GELişmiş dünYA"
şeklinde düşündüm. Açıkcası , glitter'ın çevirisi parıltı / göz alan şey /
gösterişli şey ama Rimworld'de "Glitterworld"'lar modern ve gelişmiş
dünyalar olduğu için "Gelya" olabilir. Ama olmazsa başka bir şey
türetebilirim. Veya şimdi aklıma geldi
"Geliya" - Geliyor
Tabi gelişya da olabilir ama gelişya tam gelişememiş , gelişen bir dünya
izlemini veriyor bence.
Geliya da tam bir his veremedi gibi.
Ama -ya eki mutlaka olmalı anlam ve ahenk açısından.

2017-02-01 11:24 GMT+02:00 Hüseyin Cem Aras <notifications@github.com>:

**Comment by hcemaras** [comment]
Urbworld - Kentya
Glitterworld - Teknoya
olarak kullanmaya başladım.

**Comment by Slevilex** [comment]
Oldukça iyi bir fikir Teknoya


2017-02-11 13:25 GMT+03:00 Hüseyin Cem Aras <notifications@github.com>:

**Comment by Hakkiro** [comment]
Toplam olarak konunun dısında birşey sormak istşiyorum. Testerımız varmı? yanşi yapılan çevirileri kontrol edebilecek imla harf yada çeviri hatası oldugunda soyleyebılecek bir arkadaşımız var mı çeviride?

**Comment by hcemaras** [comment]
Böyle bir alansal çalışma yok. Herkes çevirmen olarak geçiyor.

**Comment by Hakkiro** [comment]
en son kontrolleride beraber yapacağız ozaman. Bu arada telefonu kırdıgım ıcın whtsupdan yazarsanız goremem ancak sms atarsanız cvplayabılırım.

**Comment by Slevilex** [comment]
Fare ve klavye bağlamayı deneyebilirsin.

15 Şubat 2017 Çarşamba tarihinde, Hakan <notifications@github.com> yazdı:

**Comment by hcemaras** [comment]
[Satır 208](https://github.com/Ludeon/RimWorld-Turkish/edit/master/Backstories/Backstories.txt)
Caveworld - Mağaranya
olarak kullandım alternatif düşünen var mı?
