### ISSUE TITLE
plasteel

### ISSUE THREAD

**Issue by hcemaras** [Ludeon/RimWorld-Turkish#220]
**Plasteel** için çevirilerin çoğu yapılmamış, net aramasında plaçelik diye kullananlar buldum. Fakat gramer olarak baktığımda bunun yanlış olabileceğini düşündüm.
Yapı olarak bakalım
**Plasteel =**
   **1-** Pla+steel = plastic **+** steel
_(sıfat)_ Pla+çelik= _Plaçelik_ 
Anlamı: esnek/biçimlenebilir + çelik
   **2-** Plas+ teel = plastic **+** steel
Plas+ _(türetme)_ elik= _Plaselik_ 
Anlamı: Plastik+sertleştirilmiş/güçlendirilmiş

Bu açıdan bakınca Plasteel in bir çeşit çelik değil plastik olduğunu düşündüğümden, Doğru Çevirinin Plaselik olduğunu düşünüyorum.
_Sizin fikriniz nedir?_

**Comment by Hakkiro** [comment]
Sana linki attığım dosyada geçen çeviri Plastiçelik diye geçiyor. daha önce oynadığım bir oyunda Subnotica snırım oradada Plastiçelik külçe vardı. Türkçe çevirisi o şekildeydi. Yinede son tercih senindir kardeşim.

**Comment by hcemaras** [comment]
Önemli olan doğruyu bulmak, diğer türlü çeviri basit iş. 
Oyundaki anlamı Çeliğin plastikleştirilmesi (esnetilmesi) mi, yoksa Plastiğin çelikleştirilmesi(sertleştirilmesi) mi?

Böyle düşünce daha dayanıklı malzeme ürettiklerini oyundan görebiliyorum, Sonuç bana plaselik gibi geliyor. Aksi bir düşünce çıkana kadar böyle kullanmayı düşünüyorum. :)

**Comment by Slevilex** [comment]
Kelimenin kullanıcıdaki hislerine bakalım. Şahsen "Plaçelik" daha bir güçlü , heybetli gelirken "Plaselik" kauçuk gibi bir şey geliyor.
Oyunun yapısından da bakarsak Plasteel eşyalar ve yapılar Steel olanlardan kat kat kuvvetli. Bu yüzden bana plastik ile harmanlanıp refine edilmiş çelik gibi geliyor. Ve bundan dolayı ben "Plaçelik" ismini seçiyorum.
Fakat bu "Plasteel"'ı maden olarak kazabilmemiz de biraz tuhaf , yani endüstriyel bir işlem yok burada. O durumdan bakılırsa çeliğin yüzyıllar boyunca yakındaki petrolle kendi kendine refine edilmişi olması da yüksek ihtimal.
Her neyse , diğer çevirmenlerin fikrini almalıyız.
