### ISSUE TITLE
keybindings (def içindeki)

### ISSUE THREAD

**Issue by Hakkiro** [Ludeon/RimWorld-Turkish#222]
<ToggleLog.label>toggle log</ToggleLog.label>

<DebugTickOnce.label>tick once (debug)</DebugTickOnce.label>

şu iki satırı nasıl çevirirsiniz?

(debug) geliştirici modu ile alakalı bildiğim kadarı ile.

toggle = açma/kapama

powertoggle - güç açma/kapama gibi çeviri yapmıştım.

**Comment by Hakkiro** [comment]
need def > Luciferium.xml içinde anladığım kadarı ile satır eksiği var

**Comment by Slevilex** [comment]
Zaten Luciferium A16 ile kaldırıldı?

2017-02-13 14:20 GMT+03:00 Hakan <notifications@github.com>:

**Comment by Hakkiro** [comment]
ama Luciferium oyun içinde hala geçiyor.

**Comment by Hakkiro** [comment]
Yani bir sey daha . **Thrasher** kelimesinin çevirisi harmancı olarak görünüyor. ve anladığım kadarı ile korsan grubunun sınıfları gibi birşey. Ben buna torbacı desem iyi olmaz mı?

**Comment by Slevilex** [comment]
Yani , tam olarak nerede geçtiğine bağlı.

15 Şubat 2017 Çarşamba tarihinde, Hakan <notifications@github.com> yazdı:

**Comment by Hakkiro** [comment]
**PawnKindDef** içinde **PawnKinds_Pirate.txt** de **Trasher** geçiyor. bir nevi dayakçı gibi birşey de olabilir. Harman döven anlamına geliyo. harman falan diyince torbacı gibi birşey sanmıştım. Bunun yerine Tokatçı dedim :D ( Osmanlıdaki gibi )

**Comment by Hakkiro** [comment]
Arkadaşlar yorum yapılıp çözüme ulaşırsak kapatabilirsiniz konuyu. Benim açmış olmam sorun değil.
