### ISSUE TITLE
"TXT" uzantılı dosyları xmls olarak değiştirecekmiyiz?

### ISSUE THREAD

**Issue by Hakkiro** [Ludeon/RimWorld-Turkish#223]
def inj. içinde Pawn  dosyaları Txt uzantılı başka dosyalarda vardı gözüme çarpan. değiştireceksek upload yapayım?

**Comment by Slevilex** [comment]
En iyisi Tynan'a sorman.

16 Şubat 2017 Perşembe tarihinde, Hakan <notifications@github.com> yazdı:

**Comment by Hakkiro** [comment]
evet endoğrusu o tabiki. bu bir başka türkçe çeviri var güseyin de göstermiştim. onun içinde dosyların %99 u "xmls" ve oyunda sorunsuz çalışıyor. eğer dosyaları istersen mail ile sana da yollayabilirim.

**Comment by Slevilex** [comment]
Yollasan iyi olur.


2017-02-21 16:17 GMT+03:00 Hakan <notifications@github.com>:

**Comment by Hakkiro** [comment]
https://drive.google.com/open?id=0B0ZsqPi4Mi0ZVm5aa25SX3J4Tmc

drive içine attım bu linkten indirebilirsin cıkan klasörü direkt language klasorune at gitsin bizim dosya ile çakışmıyor ( bu çeviride almancadan yapılmış ama bizimkine göre baya iyi durumda)
