### ISSUE TITLE
UYUŞTURUCULAR HAKKINDA

### ISSUE THREAD

**Issue by Hakkiro** [Ludeon/RimWorld-Turkish#224]
Arkadaşlar bu uyuşturucu Adlarını ne yapıcaz?

Yani Tam olarak Çevirecekmiyiz  türkçe ye Yoksa Kendi adlarında mı bırakacağız?

Örnek; Wake-Up Uyarıcı Olarak çevirmiştim Sonradan Ayıltıcı olarak düzelttim.
Go-Juice AktiflikSuyu olarak çevrilmişti (Hüseyin çevirmişti sanırım) Bi dosyada ferhatın Tekrar Go-Juice olarak çevirdiğini gördüm.
Yayo nun çevirisini hatırlamıyorum. Payday 2 oynarken Kokain ile alakalı bir uyuştrucu olduğunu gördüm. Bu tip birşey yazılabilir.

Kimse yanlış anlamasın cidden soruyorum çünkü çevisini bitirdiğimiz her satırı tekrar elden geçirmek gerekiyor. Basa donup satırı bulmaya çalışıyorum ve gerçekten yorucu.

Şimdiden bir karar verelim ve o şekilde çevirelim. bu konuda yardımcı olup yorum yazarsanız sevinnirim. Şimdiden elinize gözünüze sağlık.

**Comment by Slevilex** [comment]
Ben çevirmiştim AktiflikSuyu olarak. Şöyle yapabiliriz.
Luciferium(bu arada oyundan kaldırılan luciferium değil malari-block'muş.) - lusiferyum
Penoxycyline - Penoksilin
Smokeleaf Joint - Sarma Sigara
Beer - Bira
Yayo -  Yayo(orjinale sadık çünkü tam bir çeviri yok.(ancak kokain gibi bir şey , burundan çekiliyor))
Wake-Up - Uyarıcı(çünkü uyarıyor , işi daha da hızlandırıyor ve uyku ihtiyacını azaltıyor)
Flake - Pipo

Şahsen benim çevirim böyle.

**Comment by Hakkiro** [comment]
Aynen bu mantıklı olmuş. tmm herkes ortak fikirde birleşirse bu şekilde çeviriye bağlı kalırız.

**Comment by hcemaras** [comment]
Gayet güzel olmuş. Wake up a aklım takıldı. Kelime Uyanmak demek olsa olsa uyandırıcı olur diye düşündüm.  Ama işi de hızlı yaptırıyor demişsin. O yüzden emin olamadım. Böyle kullanılabilir bence de. Kullanmaya başlayalım bir sorun olursa eskileri duzeltiriz.

**Comment by Hakkiro** [comment]
**Wakeup** için **Uyarıcı** yerine **Ayıltıcı** da diyebiliriz.

**Comment by Slevilex** [comment]
Bence Uyarıcı daha uygun olur çünkü Ayıltıcı sadece uykuyu alıyor ancak Uyarıcı tüm işlemleri hızlandırıyor ek olarak.

**Comment by Hakkiro** [comment]
anladım o şekilde duzeltirim ozaman. yanlız label lardaki değişiklikler çok fazla mesela almanların cevirisindeki dosylara bakıyorum.bizdeki gibi tek tek değil. tek dosya içinde label lar var. def lerin bitmesine az kaldı sanırım suanda %70-80 i bitti defler bitince bi kontrol yapıp eksiklerimize bakıcam. sonrasında key ler kalıyor. kısaca bitirmeye yakınız :) :+1:
