### ISSUE TITLE
" ACİL MESAJLARINIZ İÇİN "

### ISSUE THREAD

**Issue by Hakkiro** [Ludeon/RimWorld-Turkish#226]
**RulePackDef**  içindeki msjlar parca parca.. bu msjları tek tek çevirelim mi? Dosyaya bir bakın nedemek istediğimi daha net anlarsınız. şayet bunların tek tek çevirisini yapacaksak butun satır için kısayolların nedemek ıstedıgıne bakıp cevırmemız lazım.

**Comment by Slevilex** [comment]
Whatsapp grubumuz var mı? Bu arada kelimelerin tam Türkçe karşılıkları için TDK'yı kullanıyorum, kullanmanızı da öneriyorum. Daha Türkçe bir çeviri olur böylece.

**Comment by Slevilex** [comment]
Aramızdan boş zamanı olan bir arkadaş "Progress.md"'deki başlıkların yanına linkleri de eklese cidden hoş olur.

**Comment by hcemaras** [comment]
Progress ile ilgilenmek isterim boş vaktimde.

**Comment by sadomadolol** [comment]
Merhabalar ben yeni katıldım. Nasıl yapılacağından kısaca bahsedebilir misiniz? Teşekkürler,  iyi günler.

**Comment by hcemaras** [comment]
Hoş geldin, hcemaras@gmail.com a mail atabilirsen WhatsApp grubuna ekleyebiliriz seni.

**Comment by Slevilex** [comment]
Merhaba Mehmet, hoşgeldin.

2017-05-16 9:06 GMT+03:00 Hüseyin Cem Aras <notifications@github.com>:
