### ISSUE TITLE
Progress.md

### ISSUE THREAD

**Issue by hcemaras** [Ludeon/RimWorld-Turkish#227]
[Progress.md](https://github.com/Ludeon/RimWorld-Turkish/blob/master/Progress.md)
Link olarak yapım başlamıştır.
Örnek:
```
* [x] [RecordDef
    - [x] [Records_Misc.xml](https://github.com/Ludeon/RimWorld-Turkish/blob/master/)
```

Yapım aşaması:
Not: Son Değişiklik çift yıldız arasında gösterilmiştir. `**değişiklik**`
1) üst dosya adı kopyalanıp "RecordDef" alt dosya bağlantısı sonuna yapıştırılıp sonuna "/" işareti koyulur
 ```
* [x] [RecordDef
    - [x] [Records_Misc.xml](https://github.com/Ludeon/RimWorld-Turkish/blob/master/**RecordDef/**)
```
2) alt dosya adı kopyalanıp bağlantısının sonuna yapıştırılır
 ```
    - [x] [Records_Misc.xml](https://github.com/Ludeon/RimWorld-Turkish/blob/master/RecordDef/**Records_Misc.xml**)
```

**Comment by Slevilex** [comment]
Harikasın kardeş. Cidden faydalı olacak benim için.

28 Mart 2017 Salı tarihinde, Hüseyin Cem Aras <notifications@github.com>
yazdı:

**Comment by Hakkiro** [comment]
Vallaha hüseyin gerçekten süpersin ;) tebrik ederim. canım cıkıyodu 5-6 sekme acıp çalışmaktan :dancer: :+1: :1st_place_medal:

**Comment by hcemaras** [comment]
İyi iyi çok lazımmış demek 😊
Evde net yok olsa tamamlardım hepsini 😅

**Comment by Slevilex** [comment]
Birimiz Hüseyin'i misafir etsin 😉

31 Mart 2017 Cuma tarihinde, Hüseyin Cem Aras <notifications@github.com>
yazdı:

**Comment by Hakkiro** [comment]
Hüseyin çantanı al İstanbul büyükadaya gel beklerim :D :smile_cat:

**Comment by Slevilex** [comment]
Hazır kalkışmışken hepimiz gelelim ;) (tabii ki şaka yapıyorum 14 yaşında
taa Tarsustan İstanbula mı geleceğim :) )

2017-04-14 9:43 GMT+03:00 Hakan <notifications@github.com>:

**Comment by hcemaras** [comment]
Yaşa pek bakmıyor, ben de hadi kalkıp İstanbul'a gideyim diyemiyorum 😂

**Comment by Slevilex** [comment]
Diyorum ortaklaşa biletleri alıp mayısta tek eve toplanıp başlayıp
bitirelim 😅 (tabii ki yine ironi)

2017-04-15 11:16 GMT+03:00 Hüseyin Cem Aras <notifications@github.com>:

**Comment by Slevilex** [comment]
(Yalnız olay iyice geyiğe döndü. Beni whatsapp grubuna ekleyecek birine telefon numaramı atayım, bu arada bu issue'ları sadece biz mi görüyoruz diğer kişiler de görebiliyor mu?)

**Comment by hcemaras** [comment]
Görebiliyorlar hcemaras@gmail.com
Temizleme yaparız

**Comment by Slevilex** [comment]
Biz dediğim projede olanlar yani projede olmayanlar da görebiliyor mu?

**Comment by hcemaras** [comment]
Samet son iki çevirinin altına not düştüm. Son çeviride eksik çevirme var. Bir öncekinde ise küçük harf büyük harf hatası.
