### ISSUE TITLE
Terim Açıklaması Sorunu

### ISSUE THREAD

**Issue by Slevilex** [Ludeon/RimWorld-Turkish#228]
Atıyorum, oyunu direk Türkçe oynayan biri var. Rehberlere filan baktığında "Allah Allah, urbworld ne ola ki?" veya "Glitterworld ilacı ne la?" tarzı nidalar atabilir. Her ne kadar biz çeviri ekibi bilsek de kulanıcılar bilemeyecek. Terimler için bir sözlük-rehber tarzı bir şey yapmamız gerekiyor. 

Örnek:

Orijinal Terim - Çeviri Terimi
Urbworld           Kentya
Glitterworld       Teknoya
Caveworld         Mağaranya
...                         ...

Bu şekilde oyun içinden ulaşılabilecek bir rehber yapmamız lazım.

**Comment by Slevilex** [comment]
Özellikle hizalamıştım fakat silinmiş :(

**Comment by hcemaras** [comment]
Daha önce düşündüm, Wiki sayfası da oluşturabiliyoruz sanırım. En basit ve kullanışlı yolu bulup araştırmak lazım, biz bu terimleri açıkladık diyelim, kullanıcı bunlara nasıl erişebilir? Offline oynuyorsa ne olacak? Önce bir beyin fırtınası yapmak gerekiyor bence, ek olarak fikrine katılıyorum.

**Comment by Hakkiro** [comment]
Aynen fikir güzel. Hatta kullanışlı. Oyunun kendi wiki sayfası bulunuyor. Bildiğimiz wiki gibi işliyorsa wiki içerisine türkçe çeviride yapabiliriz. Yani tamamını çevirmektense direkt terim açıklaması yada açıklama gibi birşey yapabiliriz. Bunun dışında oyunun menu kısmında bir wiki adresi var orada bildiğiniz hikaye yazıyor. Ben çevirmek istedim fakat içinde HIM gibi oyun içerisinde Çevirmemizin istenmediği yerler mevcut.
