### ISSUE TITLE
v1.3 değişen dosyalar

### ISSUE THREAD

**Issue by LadySmith** [Ludeon/RimWorld-Turkish#316]
#315 
#305 
#307 
#303 (Backstories.xml, önceliği çok düşük ve sorunsal bir dosya)

* Liste **eksik** olmakla beraber, elimden geldiğince hızlı bir şekilde güncelliyorum. İsteyen **sıradan** başlayabilir. 
* "*Go to file*" butonu ile dosyaları ve klasörleri kolayca bulabilirsiniz.

# Üzerinde çalıştığım dosyalardan bazıları
- [x] Core\DefInjected\JobDef\Jobs_Caravan.xml
- [x] Core\Keyed\Dialog_StatsReports.xml
- [x] Core\Keyed\GameplayCommands.xml
- [x] Core\Keyed\Letters.xml
- [x] Core\Keyed\Letters.xml
- [x] Core\Keyed\Misc_Gameplay.xml
- [x] Core\Keyed\Misc_Gameplay.xml
- [x] /Core/Keyed/ -> **Tam çeviriyi tek partide atacağım**

# Temel oyun, /Core/ (~%55)
## Yeni klasörler:
- [x] /Core/DefInjected/BeardDef
- [x] /Core/DefInjected/CultureDef
- [x] /Core/DefInjected/DrugPolicyDef
- [x] /Core/DefInjected/GoodwillSituationDef
- [ ] /Core/DefInjected/HistoryEventDef
- [ ] /Core/DefInjected/IssueDef
- [ ] /Core/DefInjected/OrderedTakeGroupDef
- [x] /Core/DefInjected/PreceptDef
- [ ] /Core/DefInjected/RitualOutcomeEffectDef
- [ ] /Core/DefInjected/StyleItemCategoryDef
- [x] /Core/DefInjected/TattooDef
- [ ] /Core/DefInjected/WeaponClassDef

## Değişen dosyalar
- [ ] /Core/DefInjected/PawnColumnDef/PawnColumns_Misc.xml ([<Carry.label>](https://github.com/Ludeon/RimWorld-Turkish/blob/1e1e7e60d7352cb2d63ae1f0fa0396b01b784511/Core/DefInjected/PawnColumnDef/PawnColumns_Misc.xml#L13-L14) oyun içinden incelenmesi lazım)
- [x] #334
- [x] /Core/DefInjected/BodyPartDef/Bodies_Mechanoid.xml
- [ ] /Core/DefInjected/ConceptDef/Concepts_NotedOpportunistic.xml
- [ ] /Core/DefInjected/DamageDef/Damages_MeleeWeapon.xml
- [ ] /Core/DefInjected/DamageDef/Damages_Misc.xml
- [ ] /Core/DefInjected/FactionDef/Factions_Misc.xml
- [ ] /Core/DefInjected/HediffDef/Hediffs_Local_Misc.xml
- [ ] /Core/DefInjected/InstructionDef/Instructions.xml
- [ ] /Core/DefInjected/InteractionDef/Interactions_Animal.xml
- [x] /Core/DefInjected/NeedDef/Needs.xml
- [ ] /Core/DefInjected/PawnColumnDef/PawnColumns_Text.xml
- [x] /Core/DefInjected/PrisonerInteractionModeDef/PrisonerInteractionMode.xml
- [ ] /Core/DefInjected/QuestScriptDef/Script_DelayedRewardDropPods.xml
- [ ] /Core/Keyed/Letters.xml
- [ ] /Core/DefInjected/QuestScriptDef/Script_DelayedRewardDropPods.xml
- [ ] /Core/DefInjected/QuestScriptDef/Script_PeaceTalks.xml
- [ ] /Core/DefInjected/QuestScriptDef/Script_TransportPodCrash.xml
- [ ] #361
- [ ] /Core/DefInjected/QuestScriptDef/Scripts_Utility_ThreatsCore.xml
- [ ] /Core/DefInjected/RecipeDef/Hediffs_Local_Misc.xml
- [ ] Core/DefInjected/RulePackDef/RulePacks_Namers_People.xml
- [x] Core/DefInjected/ThoughtDef/Expectations.xml
- [ ] Core/DefInjected/ThoughtDef/Thoughts_Memory_Lost.xml
- [ ] Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
- [ ] Core/DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml
- [ ] Core/DefInjected/ThoughtDef/Thoughts_Situation_Social.xml
- [ ] Core/DefInjected/TraitDef/Traits_Singular.xml
- [ ] Core/DefInjected/ThoughtDef/Thoughts_Situation_General.xml
- [x] Core/DefInjected/ThingDef/Items_Food.xml

## Geliştirilebilir (Düşük öncelik)
- [ ] /Core/DefInjected/FactionDef/Factions_Hidden.xml ([<Insect.description>](https://github.com/Ludeon/RimWorld-Turkish/blob/master/Core/DefInjected/FactionDef/Factions_Hidden.xml#L26-L27) ve [<Mechanoid.description>](https://github.com/Ludeon/RimWorld-Turkish/blob/1e1e7e60d7352cb2d63ae1f0fa0396b01b784511/Core/DefInjected/FactionDef/Factions_Hidden.xml#L37-L38) geliştirilebilir)
- [x] /Core/DefInjected/PrisonerInteractionModeDef/PrisonerInteractionMode.xml (mevcut açıklamaların üzerine ek açıklamalar eklenmiş)
- [ ] /Core/DefInjected/RecipeDef/Recipes_Meals.xml (mevcut açıklamaların üzerine ek açıklamalar eklenmiş)
- [ ] /Core/DefInjected/StatDef/Stats_Pawns_General.xml (mevcut açıklamaların üzerine ek açıklamalar eklenmiş)
- [ ] Core/DefInjected/ThoughtDef/Thoughts_Memory_Eating.xml
- [ ] Core/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
- [x] Core/DefInjected/WorkGiverDef/WorkGivers.xml
- [ ] Core/DefInjected/ThingDef/Apparel_Headgear.xml (L31)
- [ ] Core/DefInjected/ThingDef/Apparel_Various.xml (L62)
- [ ] Core/DefInjected/ThingDef/Buildings_Exotic.xml (L17)
- [ ] Core/DefInjected/ThingDef/Buildings_Misc.xml (L104)
- [ ] Core/DefInjected/ThingDef/Items_Resource_Stuff.xml (L77)

# Royalty
## Yeni klasörler:
- [ ] /Royalty/DefInjected/CultureDef
- [ ] /Royalty/DefInjected/PlaceDef
- [ ] /Royalty/DefInjected/PreceptDef
- [ ] /Royalty/DefInjected/RitualAttachableOutcomeEffectDef
- [ ] /Royalty/DefInjected/RitualBehaviorDef
- [ ] /Royalty/DefInjected/RitualOutcomeEffectDef
- [ ] /Royalty/DefInjected/ThingStyleDef
- [ ] /Royalty/DefInjected/TransportShipDef

# Ideology
## Yeni klasörler:
- [ ] /Ideology/

# Unused
Kullanımdan kalkmış veya yeri değişmiş çeviriler. Takibi zahmetli, en son halledilecek dosyalardan.
- [ ] Core/DefInjected/JobDef/Jobs_Caravan.xml
- [ ] Core/DefInjected/PawnsArrivalModeDef/PawnsArrivalModes.xml

**Comment by AtFreezingPoint** [comment]
Altay ile yeni klasörlerin tümü üzerinde çalışıyoruz
