### ISSUE TITLE
Mechanoid terimi hakkında

### ISSUE THREAD

**Issue by Bruniikendov** [Ludeon/RimWorld-Turkish#356]
Merhaba @ajexthedev hocam. Öncelikle repoya biotech'i eklediğin için teşekkür ederim. Belirtmek istediğim ufak bir sıkıntı var. Bazı çeviri dosyalarında **mechanoid** terimini hem **mekanoid**, hem **mekanizma**, hem **mekanik**, hem de **makine** olarak çevirmişsiniz. (Biotech/Keyed/Alerts.xml örnek olarak verebilirim) Mechanoid terimi için farklı ifadeler kullanmak yerine tüm repo olarak ortak bir ifade kullanmamızın daha doğru olacağını düşünmekteyim. Düşüncelerini yorum olarak belirtirsen sevinirim. Tekrardan teşekkür ederim, iyi günler.

**Comment by ajexthedev** [comment]
Geri dönüş yaptığın için teşekkürler, Biotech dosyasını farklı bir çeviriden aldım. Bu konuya dikkat etmedim, **mekanoid** kavramının kullanılmasını daha doğru buluyorum. Boş vaktimde hepsine göz atıp düzenleyeceğim.

**Comment by Bruniikendov** [comment]
Rica ederim. Aslında elimde oyunun oluşturduğu boş bir Biotech klasörü bulunmakta. İstersen diğer çevirinin yerine o klasörü ekleyebilirim
