### ISSUE TITLE
Kurulum

### ISSUE THREAD

**Issue by Kasooooo** [Ludeon/RimWorld-Turkish#370]
Nasıl kuruyoruz?

**Comment by ennear** [comment]
[https://github.com/Ludeon/RimWorld-Turkish/wiki/Katk%C4%B1da-Bulunmak-I%C3%A7in](url)

**Comment by ennear** [comment]
[](url)

**Comment by ennear** [comment]
[Katkıda Bulunmak için](https://github.com/Ludeon/RimWorld-Turkish/wiki/Katk%C4%B1da-Bulunmak-I%C3%A7in)
