### ISSUE TITLE
yeni dlc ne zaman güncellenir bilgi var mı

### ISSUE THREAD

**Issue by SherlockOsman** [Ludeon/RimWorld-Turkish#396]
yeni dlc ne zaman güncellenir bilgi var mı

**Comment by hollmmes** [comment]
eğer çeviri içinse ben dosyalarını pull request olarak yükledim birazını çevirerek ama bakılmadı hala galiba

**Comment by Talarus** [comment]
Ben DLC çıktığı ilk günlerde kendi çeviri dosyamda %30-40 ını çevirmiştim. Sonra birisi gelip bu yamayı sadece ben çevirdim benden başka kimse çevirmedi diye katkı sağlayan herkesin adını silip sadece kendi reklamını yaptığını gördüm. Üstüne de herkese ağır küfürler etti. Ondan sonra soğudum, kalan kısımları çevirmeyi bıraktım. Buraya katkı yapmamamın tek sebebi o tip kişilerdir.

**Comment by SherlockOsman** [comment]
var öyle tiplerde önemli değil ya önemli olan çevrilip herkesin oynayabilmesi. yani ben dosyaları bulamadım çevirecektim.

**Comment by SherlockOsman** [comment]
çevirmeye arkadaşlar başlamış harika bir kısmı çevrilmiş. umarım bu hafta biter. bende akşam kalan kısmı çevireyim

**Comment by hollmmes** [comment]
Ben anomaly dosyalarını yükledim şu an cevirisi yapılabilir staj işimden sonra bende devam edeceğim hızlıca

**Comment by Komaedaxs** [comment]
acaba hala 1.5 sürümünü çevirmeyle ilgileniyor musunuz? @SherlockOsman @hollmmes

**Comment by hollmmes** [comment]
Evet neden

**Comment by Komaedaxs** [comment]
@hollmmes yardımda bulunmak istiyorum

**Comment by SabriAlkan** [comment]
Dostlarım selamlar,çeviri konusunda destek olamıyorum ama çevirinin çıkmasını dört gözle bekliyorum.Emeğinize sağlık

**Comment by SabriAlkan** [comment]
@SherlockOsman çeviri ne durumda?
