### ISSUE TITLE
Anomaly dlc çevirisi devam ediyor mu?

### ISSUE THREAD

**Issue by samiDumut** [Ludeon/RimWorld-Turkish#398]
Çeviri devam ediyor mu?

**Comment by SherlockOsman** [comment]
arkadaşın biri yapıyorum dedi ama büyük ihtimalle gelmeyecek ya da 5 6 ay sonra belki

**Comment by hollmmes** [comment]
Yapıyorum ama sınav sürecim hala bitmedi şu an finallerimin 3. Günü

29 May 2024 Çar 21:37 tarihinde SherlockOsman ***@***.***>
şunu yazdı:
