### ISSUE TITLE
Anomaly çeviride son durum nedir?

### ISSUE THREAD

**Issue by SherlockOsman** [Ludeon/RimWorld-Turkish#399]
Beyler oyuna her girdiğimde hata alıyorum dille ilgili nasıl olacak çözümü çeviri yapılmadı mı ve yapıldıysa bir kısmı yüklendi mi oyuna çünkü dille ilgili sürekli hata alıyorum.

**Comment by denizubu** [comment]
bir terslik olmazsa bu hafta içerisinde hazır olacak.

**Comment by denizubu** [comment]
Tekrardan selamlar. Çeviri tamamlandı ve eklendi. İyi oyunlar.
